export const beautyServices = [
  {
    id: "1",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "1",
    category: "Peluquería",
    idServiceCategory: "1",
    serviceCategory: "Color",
    servicePrice: 500,
    serviceDiscount: 30,
  },
  {
    id: "2",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "1",
    category: "Peluquería",
    idServiceCategory: "2",
    serviceCategory: "Mechas",
    servicePrice: 600,
  },
  {
    id: "3",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "1",
    category: "Peluquería",
    idServiceCategory: "3",
    serviceCategory: "Peinado",
    servicePrice: 400,
  },
  {
    id: "4",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "2",
    category: "Barbería",
    idServiceCategory: "1",
    serviceCategory: "Corte de pelo",
    servicePrice: 500,
    serviceDiscount: 15,
  },
  {
    id: "5",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "2",
    category: "Barbería",
    idServiceCategory: "2",
    serviceCategory: "Barba",
    servicePrice: 500,
    serviceDiscount: 20,
  },
  {
    id: "6",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "1",
    serviceCategory: "Extensiones de pestañas",
    servicePrice: 500,
  },
  {
    id: "7",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "2",
    serviceCategory: "Laminado de cejas",
    servicePrice: 500,
    serviceDiscount: 30,
  },
  {
    id: "8",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "2",
    serviceCategory: "Laminado de cejas",
    servicePrice: 500,
    serviceDiscount: 30,
  },
  {
    id: "9",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "2",
    serviceCategory: "Laminado de cejas",
    servicePrice: 500,
    serviceDiscount: 30,
  },
  {
    id: "10",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "2",
    serviceCategory: "Laminado de cejas",
    servicePrice: 500,
    serviceDiscount: 30,
  },
  {
    id: "11",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "2",
    serviceCategory: "Laminado de cejas",
    servicePrice: 500,
    serviceDiscount: 30,
  },
  {
    id: "12",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "2",
    serviceCategory: "Laminado de cejas",
    servicePrice: 500,
    serviceDiscount: 30,
  },
  {
    id: "13",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "2",
    serviceCategory: "Laminado de cejas",
    servicePrice: 500,
    serviceDiscount: 30,
  },
  {
    id: "14",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "2",
    serviceCategory: "Laminado de cejas",
    servicePrice: 500,
    serviceDiscount: 30,
  },
  {
    id: "15",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "2",
    serviceCategory: "Laminado de cejas",
    servicePrice: 500,
    serviceDiscount: 30,
  },
  {
    id: "16",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "2",
    serviceCategory: "Laminado de cejas",
    servicePrice: 500,
    serviceDiscount: 30,
  },
  {
    id: "17",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "2",
    serviceCategory: "Laminado de cejas",
    servicePrice: 500,
    serviceDiscount: 30,
  },
  {
    id: "18",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "2",
    serviceCategory: "Laminado de cejas",
    servicePrice: 500,
    serviceDiscount: 30,
  },
  {
    id: "19",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "2",
    serviceCategory: "Laminado de cejas",
    servicePrice: 500,
    serviceDiscount: 30,
  },
  {
    id: "20",
    idProf: "1",
    title: "Diego Teplitzky",
    idCategory: "3",
    category: "Estética",
    idServiceCategory: "2",
    serviceCategory: "Laminado de cejas",
    servicePrice: 500,
    serviceDiscount: 30,
  },
];
