const Images = [{ image: require("../assets/user.png") }];

export const comments = [
  {
    id: "1",
    name: "Diego",
    comment: `Muy buen servicio!`,
    image: Images[0].image,
    rating: 5,
    date: "10/04/2021",
  },
  {
    id: "2",
    name: "Jose",
    comment: `Buen servicio`,
    image: Images[0].image,
    rating: 4,
    date: "10/04/2021",
  },
  {
    id: "3",
    name: "Lucía",
    comment: `Normal`,
    image: Images[0].image,
    rating: 3,
    date: "10/04/2021",
  },
  {
    id: "4",
    name: "Camila",
    comment: `Excelente profesional!`,
    image: Images[0].image,
    rating: 5,
    date: "10/04/2021",
  },
  {
    id: "5",
    name: "Gonzalo",
    comment: `Excelente profesional!`,
    image: Images[0].image,
    rating: 5,
    date: "10/04/2021",
  },
  {
    id: "6",
    name: "Diego",
    comment: `Excelente profesional!`,
    image: Images[0].image,
    rating: 5,
    date: "10/04/2021",
  },
  {
    id: "7",
    name: "Diego",
    comment: `Excelente profesional!`,
    image: Images[0].image,
    rating: 5,
    date: "10/04/2021",
  },
];
