const ImagesProf = [
  { image: require("../assets/banners/prof1.jpg") },
  { image: require("../assets/banners/prof2.jpg") },
  { image: require("../assets/banners/prof3.jpg") },
  { image: require("../assets/banners/prof4.jpg") },
  { image: require("../assets/banners/prof5.jpg") },
];

const ImagesUser = [
  { image: require("../assets/banners/prof1.jpg") },
  { image: require("../assets/banners/prof2.jpg") },
  { image: require("../assets/banners/prof3.jpg") },
  { image: require("../assets/banners/prof4.jpg") },
  { image: require("../assets/banners/prof5.jpg") },
];

export const shift = [
  {
    id: "1",
    idUser: "1",
    nameUser: "Martin Rodriguez",
    idProf: "1",
    nameProf: "Diego Teplitzky",
    idCategory: "1",
    category: "Peluquería",
    idServiceCategory: "1",
    serviceCategory: "Mechas",
    servicePrice: 600,
    day: "Lunes",
    hour: "9:00",
    date: "Lunes 19 de Abril de 2021",
    imageProf: ImagesProf[0].image,
    imageUser: ImagesUser[0].image,
    paymentMethod: "Efectivo",
    userAdress: "Rivadavia 5000",
    neighborhood: "Caballito",
    userMail: "user@gmail.com",
    profMail: "prof@gmail.com",
    userPhone: "11111111",
    profPhone: "11111111",
  },
  {
    id: "2",
    idUser: "2",
    nameUser: "Rodolfo Paez",
    idProf: "2",
    nameProf: "Juan Gonzalez",
    idCategory: "2",
    category: "Barbería",
    idServiceCategory: "1",
    serviceCategory: "Corte de pelo",
    servicePrice: 500,
    day: "Martes",
    hour: "10:00",
    date: "Martes 20 de Abril de 2021",
    imageProf: ImagesProf[1].image,
    imageUser: ImagesUser[1].image,
    paymentMethod: "Tarjeta de crédito",
    userAdress: "Rivadavia 5000",
    neighborhood: "Caballito",
    userMail: "user@gmail.com",
    profMail: "prof@gmail.com",
    userPhone: "11111111",
    profPhone: "11111111",
  },
  {
    id: "3",
    idUser: "1",
    nameUser: "Martin Rodriguez",
    idProf: "1",
    nameProf: "Diego Teplitzky",
    idCategory: "1",
    category: "Peluquería",
    idServiceCategory: "3",
    serviceCategory: "Peinado",
    servicePrice: 400,
    day: "Viernes",
    hour: "14:00",
    date: "Viernes 16 de Abril de 2021",
    imageProf: ImagesProf[2].image,
    imageUser: ImagesUser[2].image,
    paymentMethod: "Efectivo",
    userAdress: "Rivadavia 5000",
    neighborhood: "Caballito",
    userMail: "user@gmail.com",
    profMail: "prof@gmail.com",
    userPhone: "11111111",
    profPhone: "11111111",
  },
  {
    id: "4",
    idUser: "1",
    nameUser: "Martin Rodriguez",
    idProf: "4",
    nameProf: "Javier Cillis",
    idCategory: "3",
    category: "Depilacion",
    idServiceCategory: "1",
    serviceCategory: "Depilación de cintura",
    servicePrice: 800,
    day: "Jueves",
    hour: "17:00",
    date: "Jueves 15 de Abril de 2021",
    imageProf: ImagesProf[3].image,
    imageUser: ImagesUser[3].image,
    paymentMethod: "Tarjeta de crédito",
    userAdress: "Rivadavia 5000",
    neighborhood: "Caballito",
    userMail: "user@gmail.com",
    profMail: "prof@gmail.com",
    userPhone: "11111111",
    profPhone: "11111111",
  },
];
